### ISSUE TITLE
InfluxDB Error: database not found: collectd

### ISSUE THREAD

**Issue by agpol07** [TheCry/synology-fritzbox-grafana#3]
I have the same problem as the other guys.
I've followed all the Troubleshoot you made, with no luck.
Synology works perfect..

![image](https://user-images.githubusercontent.com/52812577/217108210-7467fab8-6c89-4633-b431-c5badc3a5794.png)
![image](https://user-images.githubusercontent.com/52812577/217108321-851dd58a-1cc8-4ed0-aec7-6414a01f3b2e.png)

**Comment by TheCry** [comment]
Did you read the last comment:
https://github.com/TheCry/synology-fritzbox-grafana/issues/2#issuecomment-1019536949

**Comment by NWolkow** [comment]
@agpol07 still having the issue? I ve got the same issue, read and followed the above mentiond thread as well as the last comment. It doesn t help.

Somehow it looks like the database "collectd" has not been set up at any point. Looking at the influx db-structure just shows the DBs "_internal" and "telegraf" which explains the perfectly working dashboard for the synology diskstation. 

at what point the collectd database should have been set up?

Edit:
I created the DB manually via CLI. Grafana is able to connect but of course there is nothing in to visualise...
In the logs of the FritzBox i can see that there is a successful logon with the user given to fritzcollectd.
